[project]
name = "laser-backend"
version = "0.1.0"
description = "Backend for 5DOF laser system"
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.119.1",
    "geometry3d>=0.3.0",
    "matplotlib>=3.10.7",
    "pillow>=12.0.0",
    "pydantic>=2.12.3",
    "pydantic-settings>=2.11.0",
    "pytest>=8.4.2",
    "uvicorn>=0.38.0",
    "vpython>=7.6.5",
    "svgpathtools>=1.7.1",
    "gcode-lib",
    "websockets>=16.0",
    "mpl-interactions>=0.24.2",
    "setuptools<81",
    "pyserial>=3.5",
    "svgelements>=1.9.6",
    "pytest-mock>=3.15.1",
    "networkx>=3.6.1",
    "rustworkx>=0.17.1",
    "pandas>=3.0.3",
    "streamlit>=1.58.0",
]

[dependency-groups]
dev = ["mock>=5.2.0", "pre-commit-uv==4.2.0", "ruff>=0.14.14"]


[tool.pytest.ini_options]
pythonpath = [""]

[tool.uv.sources]
gcode-lib = { git = "https://github.com/HCI-BP-25-26/gcode_lib.git" }
